services:
  - type: web
    name: sk-rozaana-bazaar
    runtime: docker
    plan: free
    region: oregon
    envVars:
      - key: PORT
        value: 8080
      - key: DB_URL
        value: jdbc:mysql://bamupc1fh4jwu1sxij7n-mysql.services.clever-cloud.com:3306/bamupc1fh4jwu1sxij7n
      - key: DB_USER
        value: uw1i0y5e163vztxv
      - key: DB_PASSWORD
        value: VQzfMMHPpqHquYUleFyx
